// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAywpsFVQeUnmMPhowBmvYedD7OfaKdwcs',
    appId: '1:294833618298:web:53362b76482a1dca11aac3',
    messagingSenderId: '294833618298',
    projectId: 'finease-e7b55',
    authDomain: 'finease-e7b55.firebaseapp.com',
    storageBucket: 'finease-e7b55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1sgGZgwQql2ArJFnmrcELHP4APLwoXE',
    appId: '1:294833618298:android:a48c86c889e0a93011aac3',
    messagingSenderId: '294833618298',
    projectId: 'finease-e7b55',
    storageBucket: 'finease-e7b55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNdbhc0NYQw9ATyQ6-ETlHLNP2k22x5Y',
    appId: '1:294833618298:ios:fe25ed139514acdc11aac3',
    messagingSenderId: '294833618298',
    projectId: 'finease-e7b55',
    storageBucket: 'finease-e7b55.appspot.com',
    iosClientId: '294833618298-aaop4v3s2nurgj9bmj6gvaukia3hlc5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.finEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhNdbhc0NYQw9ATyQ6-ETlHLNP2k22x5Y',
    appId: '1:294833618298:ios:362ac14fb71c03ce11aac3',
    messagingSenderId: '294833618298',
    projectId: 'finease-e7b55',
    storageBucket: 'finease-e7b55.appspot.com',
    iosClientId: '294833618298-b0v9h8v8k30qiv51likbhlrcgfef6kav.apps.googleusercontent.com',
    iosBundleId: 'com.example.finEase.RunnerTests',
  );
}
